# Generated by Django 3.1.3 on 2021-08-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1)),
                ('data', models.FileField(upload_to='Alphabet/')),
            ],
        ),
    ]
